### ISSUE TITLE
Login issue 

### ISSUE THREAD

**Issue by knkrth** [onsightit/web-wallet#2]
Hi, I setup everything correct & I start the wallet, I can see the login page but when I enter the login details and hit enter it redirect me to home page I don't know why?

**Comment by grumpydevelop** [comment]
same

**Comment by SirPadde** [comment]
Within the settings.json

`// The url hosting the app. e.g. myhost.org (must match browser URI to satisfy CORS)
  "appHost":`

solved this issue for me.

**Comment by knkrth** [comment]
Did @SirPadde solved your problem @grumpydevelop ? Can you login to home page? If so can you share a screen short of home page?

**Comment by grumpydevelop** [comment]
@knkrth i just writed ip in appHost and everything is working ok

**Comment by knkrth** [comment]
@grumpydevelop Ok, Let me try it out when I am free.

**Comment by exander77** [comment]
Have the same problem, but setting appHost: "" does not help. Also do get no error messages in the browser, it just redirects back to the login page.

**Comment by exander77** [comment]
It is really frustrating, no errors in the browser, no errors in nodejs console, but I cannot login.

**Comment by grumpydevelop** [comment]
@exander77 write me in telegram @maxzambinq

**Comment by steveieee** [comment]
This is likely a CORS issue,  In settings.json, the appHost must match the browser's URL.

**Comment by onsightit** [comment]
This is likely a CORS issue, In settings.json, the appHost must match the browser's URL.

**Comment by exander77** [comment]
@onsightit Nope, in lib/init-wallet.js:
There is:
newUser.local.password = newUser.generateHash("password");
instead of:
newUser.local.password = newUser.generateHash(coin.settings.masterPassword);

**Comment by exander77** [comment]
Also, js files does not respect chRoot. And do not append /wallet in front of them.
And sometimes it cannot be shut down by CTRL+C and it is left hanging.
Also wallet console is not protected and I can manipulate it even without been logged.

I thought it was a good web wallet, but seems not so good so far.

**Comment by exander77** [comment]
Also I cannot register a user, if I try Sign Up and send the form I does nothing. When I click "Sign Up", it sends the form, no error is produced and I am back at the empty from.

Should I create issues for everything I find?

**Comment by exander77** [comment]
Just updated, and cleared the db. After first login I am forced to update profile, but I get "Save Error!". Awesome update. :)

**Comment by exander77** [comment]
Also signup page now returns an error.

**Comment by exander77** [comment]
In routes/users.js is some sequalize variable which is not defined.

**Comment by onsightit** [comment]
Give me a couple more hours. Trying to merge in a few changes from another project of mine. ;) On Jan 28, 2018 10:05 AM, "Ing. Radomír Polách" <notifications@github.com> wrote:In routes/users.js is some sequalize variable which is not defined.

**Comment by exander77** [comment]
No problem. :) It is your project.

I am ready to test anything with fresh DB. So it may be helpful for you to make the project viable for others.

**Comment by onsightit** [comment]
Thanks for the great feedback, exander77.  2.1.3 is ready for beta...
